---
before:
  hooks:
    - go mod download

builds:
  - main: ./cmd/tfcheck/main.go
    id: tfcheck
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -buildid="" -s -w -X main.version={{.Version}}

archives:
  - format_overrides:
      - goos: windows
        format: zip
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}'

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: '{{ .Version }}-{{ .ShortCommit }}'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  prerelease: auto

brews:
  - name: tfcheck
    description: Template for go project and tap.
    homepage: https://github.com/itsdalmo/tfcheck
    install: |
      bin.install "tfcheck"
    test: |
      system "#{bin}/tfcheck --version"
    tap:
      owner: itsdalmo
      name: homebrew-tap
    folder: Formula
