---
name: test

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: '3.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install goreleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: v1.18
          install-only: true

      - name: Go build (with goreleaser)
        run: task build

      - name: Check git status
        run: |
          status=$(git status --porcelain)
          if [ -n "${status}" ]; then
            echo "Diff in generated files and/or formatting:"
            echo "${status}"
            exit 1
          fi
